# Sources
tap 'caskroom/cask'
tap 'homebrew/cask-fonts'

# CLI Utilities
brew 'bash-completion'
brew 'git'
brew 'libdvdcss'
brew 'trash'
brew 'nano'
brew 'imagemagick'
brew 'wget'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'

# Fonts
cask 'font-fira-code'
cask 'font-fira-mono'

# Apps
cask 'adobe-creative-cloud'
cask 'appcleaner'
cask 'backblaze'
cask 'chatology'
cask 'doxie'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'iina'
cask 'imazing'
cask 'kaleidoscope'
cask 'little-snitch'
cask 'makemkv'
cask 'max'
cask 'micro-snitch'
cask 'rescuetime'
cask 'rocket'
cask 'sketch'
cask 'soulver'
cask 'spamsieve'
cask 'superduper'
cask 'transmission'
cask 'undercover'
cask 'unison'
cask 'unlox'
cask 'vanilla'
cask 'virtualbox'
cask 'visual-studio-code'

# Screen Saver
cask 'aerial'
