# Sources
tap 'caskroom/cask'

# CLI Utilities
echo '📦 Installing CLI Tools'
brew 'git'
brew 'libdvdcss'
brew 'trash'
brew 'nano'
brew 'imagemagick --with-webp'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'

# Apps
echo '📦 Installing applications'
cask 'adobe-creative-cloud'
cask 'appcleaner'
cask 'backblaze'
cask 'chatology'
cask 'doxie'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'imazing'
cask 'imazing-mini'
cask 'kaleidoscope'
cask 'little-snitch'
cask 'micro-snitch'
cask 'rescuetime'
cask 'rocket'
cask 'sketch'
cask 'soulver'
cask 'spamsieve'
cask 'superduper'
cask 'transmission'
cask 'undercover'
cask 'unison'
cask 'unlox'
cask 'vanilla'
cask 'virtualbox'
cask 'visual-studio-code'

# Screen Saver
echo '📦 Installing screen savers'
cask 'aerial'

# Remove outdated versions from the cellar.
brew cleanup
